### ISSUE TITLE
configure script does not support '--without-PACKAGE' syntax

### ISSUE THREAD

**Issue by rjbarnet** [resiprocate/resiprocate#155]
When trying to explicitly disable support for a package using the '--without-PACKAGE' syntax, it will actually enable support for the package. For example if you run:

`./configure --without-openssl`, the build will be configured to try to build with OpenSSL support.

**Comment by tpetazzoni** [comment]
The issue comes from the fact that the AC_ARG_WITH() macro was misunderstood, and it's a common mistake. Many people think the syntax is AC_ARG_WITH(name, help, action-if-enabled, action-if-disabled), but the actual syntax is AC_ARG_WITH(name, help, action-if-specified, action-if-unspecified). I.e the action-if-specified is executed when some value is passed, either positive (--with-something) or negative (--without-something) while the action-if-unspecified is executed when no value at all is passed for this option. See https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/External-Software.html for more details.
