### ISSUE TITLE
sipXtapi version to use to compile recon VS 15 solution

### ISSUE THREAD

**Issue by simone-gaiarin** [resiprocate/resiprocate#160]
I am trying to compile the Visual Studio solution `recon_15_0.sln` from the branch `resiprocate-1.12` (the latest stable build).

The solution refers to projects of `sipXtapi` with the suffix `-msvc8` and extension `vcxproj` but those do not exist anywhere in the code of `sipXtapi`.

Using the tag `3.3.0~test18` from this repo https://github.com/sipXtapi/sipXtapi (which is outdate btw) I can open the `sipX-msvc8.sln` solution file and migrate all the `.vcproj` projects to a newer version of VS (2019 in my case) so that the projects  `-msvc8.vcxproj` are created, but at this point `sipXtapi` does not compile. 

Otherwise in the solution I can replace the file with the `-msvc8` with the `.vcxproj` file now provided in the `master` branch of `sipXtapi`. This however breaks all the references in the projects of the solution.

Wat version of `sipXtapi` was used to build resiprocate-1.12? (and from which repo git or svn was it taken)

**Comment by sgodin** [comment]
Hi Simone,

The recon wiki page contains details on the correct sipXtapi location:
https://www.resiprocate.org/Recon_Overview

Main pointers are:
sipXTapi wiki:  http://sipxwiki.sipez.com/wiki/SipXtapi
SVN:  http://sipxsvn.sipez.com/rep/sipX/main/
GIT Mirror:  https://github.com/sipXtapi/sipXtapi-svn-mirror

Scott

**Comment by simone-gaiarin** [comment]
Hi,
sorry maybe it was not clear what my problem is. I already know where the repositories are.

The recon VS project refers to some files that are not present in the sipXtapi (or at least not in the current master). I need to know what version (or commit number) of sipXtapi was used for the stable version 1.12 of resiprocate. resiprocate has projects for VS 2017 that refer to sipXtapi VS projects that are missing in master.

Each stable version of resiprocate should refer to a single version of sipXtapi (maybe in the changelog) or have the sipXtapi git respository as a submodule, otherwise compiling it on Windows against a random version of sipXtapi is going to be a mess each time.

**Comment by sgodin** [comment]
We currently do not track the versions of sipXtapi, since it hasn't been
changing very often, but I understand the value in that.

At one point in time the recon.sln was pointing to the existing .vcproj
files and just opening the recon solution was all that was required to have
them auto upgraded, but it seems a recon.sln file got committed with the
new naming.    Sorry about that.  In that case, your approach of opening
the sipx.sln solution to get the .vcxproj files created is the correct
one.  There is more needed though, in order to get things compiled for
recon, outlined here:
https://www.resiprocate.org/Building_recon#Setting_up_the_build_environment

The recon readme.txt has this info on the minimum version, but there is no
documented max version at this point:
Note: Ensure you use at least SVN revision 11413 of sipXtapi.

Hope this helps,

Scott

**Comment by simone-gaiarin** [comment]
Thanks for the answer. 

I managed to compile it somehow, but I had to add some fix here and there. This is probably due to the fact that I am using VS 2019 and a different version of sipXtapi.

If in the future you can track the SVN version of sipXtapi for the stable releases of resiprocate, it would be great.

**Comment by sgodin** [comment]
Closing this issue.  Note:  We have added full VS2019 support for recon and the latest sipX code base.
